// Code generated by dein. DO NOT EDIT.
package main

import (
	car_2 "github.com/suger-131997/dein/example/car"
	engine_2 "github.com/suger-131997/dein/example/car/engine"
	light_2 "github.com/suger-131997/dein/example/car/light"
	wheel_2 "github.com/suger-131997/dein/example/car/wheel"
)

type Container struct {
	ICar car_2.ICar
}

func NewContainer(
	engineType engine_2.EngineType,
	__funcLight func() light_2.Light,
) (*Container, error) {
	__c := &Container{}

	engine, err := engine_2.NewEngine(engineType)
	if err != nil {
		return nil, err
	}
	light := __funcLight()
	wheel := wheel_2.NewWheel()
	car := car_2.NewCar(engine, wheel, light)
	var iCar car_2.ICar = car
	__c.ICar = iCar

	return __c, nil
}
