// Code generated by dein. DO NOT EDIT.
package main

import (
	car_2 "github.com/suger-131997/dein/example/car"

	engine_2 "github.com/suger-131997/dein/example/car/engine"

	wheel_2 "github.com/suger-131997/dein/example/car/wheel"
)

type Container struct {
	Car *car_2.Car
}

func NewContainer(
	engineType engine_2.EngineType,
) (*Container, error) {
	c := &Container{}

	engine, err := engine_2.NewEngine(engineType)
	if err != nil {
		return nil, err
	}
	wheel := wheel_2.NewWheel()
	car := car_2.NewCar(engine, wheel)
	c.Car = car

	return c, nil
}
