// Code generated by dein. DO NOT EDIT.
package main

import (
	car1 "github.com/suger-131997/dein/example/car"

	engine1 "github.com/suger-131997/dein/example/car/engine"

	wheel1 "github.com/suger-131997/dein/example/car/wheel"
)

type Container struct {
	Car *car1.Car
}

func NewContainer(
	engineType engine1.EngineType,
) (*Container, error) {
	c := &Container{}

	engine, err := engine1.NewEngine(engineType)
	if err != nil {
		return nil, err
	}
	wheel := wheel1.NewWheel()
	car := car1.NewCar(engine, wheel)
	c.Car = car

	return c, nil
}
