run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gci
    - gofumpt
    - unconvert
    - whitespace
    - wsl

linters-settings:
  gci:
    sections:
      - "standard"
      - "default"
      - "prefix(github.com/suger-131997/dein)"
      - "blank"
      - "dot"
  gofumpt:
    extra-rules: true