version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - unconvert
    - whitespace
    - wsl

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - "standard"
        - "default"
        - "prefix(github.com/suger-131997/dein)"
        - "blank"
        - "dot"
    gofumpt:
      extra-rules: true