// Code generated by dein. DO NOT EDIT.
package main

import (
	a "github.com/suger-131997/dein/internal/testpackages/a"
	b_3 "github.com/suger-131997/dein/internal/testpackages/b"
)

type Container struct {
}

func NewContainer(
	a1 a.A1,
	b b_3.B,
) (*Container, error) {
	__c := &Container{}

	var iA1 a.IA1 = b
	b_2 := b_3.NewB(a1)

	return __c, nil
}
