// Code generated by dein. DO NOT EDIT.
package main

import (
	a "github.com/suger-131997/dein/internal/testpackages/a"
)

type Container struct {
	A1 a.A1
}

func NewContainer() (*Container, error) {
	__c := &Container{}

	a1 := a.NewA1()
	__c.A1 = a1

	return __c, nil
}
