// Code generated by dein. DO NOT EDIT.
package main

import (
	a "github.com/suger-131997/dein/internal/testpackages/a"
)

type Container struct {
	a1 a.A1
}

func (c *Container) A1() a.A1 {
	return c.a1
}

func NewContainer() (*Container, error) {
	__c := &Container{}

	a1 := a.NewA1()
	__c.a1 = a1

	return __c, nil
}
