// Code generated by dein. DO NOT EDIT.
package main

import (
	a "github.com/suger-131997/dein/internal/testpackages/a"
)

type Container struct {
	a2 a.A2
}

func (c *Container) A2() a.A2 {
	return c.a2
}

func NewContainer(
	a1_2 *a.A1,
) (*Container, error) {
	__c := &Container{}

	a1 := a.NewA1()
	a2 := a.NewA2(a1, a1_2)
	__c.a2 = a2

	return __c, nil
}
