// Code generated by dein. DO NOT EDIT.
package main

import (
	a "github.com/suger-131997/dein/internal/testpackages/a"
	b_2 "github.com/suger-131997/dein/internal/testpackages/b"
)

type Container struct {
	b *b_2.B
}

func (c *Container) B() *b_2.B {
	return c.b
}

func NewContainer() (*Container, error) {
	__c := &Container{}

	a1 := a.NewA1()
	b := b_2.NewB(a1)
	__c.b = b

	return __c, nil
}
